repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v1.2.1
    hooks:
    -   id: autopep8-wrapper
    -   id: check-added-large-files
    -   id: check-builtin-literals
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
    -   id: flake8
    -   id: mixed-line-ending
    -   id: name-tests-test
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v1.0.1
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/asottile/pyupgrade.git
    sha: v1.2.0
    hooks:
    -   id: pyupgrade
        args: ['--py3-plus']
-   repo: https://github.com/asottile/add-trailing-comma.git
    sha: v0.6.4
    hooks:
    -   id: add-trailing-comma
        args: ['--py35-plus']
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    sha: v1.1.4
    hooks:
    -   id: remove-tabs
-   repo: local
    hooks:
    -   id: app-templates-prefixed-with-app-name
        # https://github.com/ocf/ocfweb/blob/3a4517c6f06f0/.pre-commit-config.yaml#L54-L66
        # has more details on why this is a problem. The general idea is that
        # having multiple apps in Django can lead them to conflict with each other
        # if they have the same template name
        language: system
        name: App templates must be prefixed with app name
        entry: bash -c 'echo "Make sure to prefix your template directories!" && exit 1'
        files: ^hknweb/[^/]+/templates/[^/]+\.html$
