language: python
dist: xenial
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.7"
  - "3.8"
  - "3.9"
env:
  # TODO: add test env (where DEBUG=False, secret key unencrypted)
  - HKNWEB_MODE=dev
install:
  - make venv
  - source .venv/bin/activate
  - make install
script:
  - make migrate
  - .venv/bin/python ./manage.py check
